---
name: concourse
product_version: $( version )
minimum_version_for_upgrade: 0.0.1
label: Concourse 7.9
rank: 1
metadata_version: 3.0.3
original_metadata_version: '1.8'
service_broker: false
opsmanager_syslog: false
requires_product_versions:
- name: cf
  version: '>=1.0'
icon_image: $( icon )
serial: true
variables:
- name: postgres_password
  type: password
- name: token_signing_key
  type: rsa
- name: tsa_host_key
  type: ssh
- name: worker_key
  type: ssh
releases:
- $( release "bpm" )
- $( release "concourse" )
- $( release "postgres" )
- $( release "routing" )
stemcell_criteria:
  os: ubuntu-jammy
  version: "1"
  enable_patch_security_updates: true
property_blueprints:
- $( property "credentials" )
- $( property "external_url" )
- $( property "tls_credentials" )
- $( property "auth_selector" )
- $( property "secrets_selector" )
- $( property "gorouter_selector" )
- $( property "tagged_worker_tag" )
form_types:
- $( form "settings" )
- $( form "secrets" )
- $( form "routing" )
job_types:
- $( instance_group "web" )
- $( instance_group "worker" )
- $( instance_group "tagged_worker" )
- $( instance_group "db" )
